export type SupabaseSession = { access_token: string; refresh_token?: string; user?: { id: string; email?: string } };
const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || "";
const publishableKey = process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY || "";
export const supabaseConfig = { url: supabaseUrl, key: publishableKey, ready: Boolean(supabaseUrl && publishableKey) };
function h(token?: string): HeadersInit { return { apikey: publishableKey, Authorization: `Bearer ${token || publishableKey}`, "Content-Type": "application/json" }; }
export async function login(email: string, password: string): Promise<SupabaseSession> { const res = await fetch(`${supabaseUrl}/auth/v1/token?grant_type=password`, {method:"POST",headers:{apikey:publishableKey,"Content-Type":"application/json"},body:JSON.stringify({email,password})}); const data=await res.json(); if(!res.ok) throw new Error(data?.error_description||data?.msg||"Giriş yapılamadı."); return data; }
export async function register(email: string, password: string): Promise<SupabaseSession> { const res = await fetch(`${supabaseUrl}/auth/v1/signup`, {method:"POST",headers:{apikey:publishableKey,"Content-Type":"application/json"},body:JSON.stringify({email,password})}); const data=await res.json(); if(!res.ok) throw new Error(data?.error_description||data?.msg||"Kayıt oluşturulamadı."); return data; }
export async function selectRows<T>(table:string, token:string, query="select=*&order=created_at.desc") { const res=await fetch(`${supabaseUrl}/rest/v1/${table}?${query}`,{headers:h(token),cache:"no-store"}); const data=await res.json(); if(!res.ok) throw new Error(data?.message||`${table} okunamadı.`); return data as T[]; }
export async function insertRow<T>(table:string, token:string, payload:Record<string,unknown>) { const res=await fetch(`${supabaseUrl}/rest/v1/${table}`,{method:"POST",headers:{...h(token),Prefer:"return=representation"},body:JSON.stringify(payload)}); const data=await res.json(); if(!res.ok) throw new Error(data?.message||`${table} kaydedilemedi.`); return data?.[0] as T; }
export async function updateRow<T>(table:string, token:string, id:string, payload:Record<string,unknown>) { const res=await fetch(`${supabaseUrl}/rest/v1/${table}?id=eq.${id}`,{method:"PATCH",headers:{...h(token),Prefer:"return=representation"},body:JSON.stringify(payload)}); const data=await res.json(); if(!res.ok) throw new Error(data?.message||`${table} güncellenemedi.`); return data?.[0] as T; }
export async function deleteRow(table:string, token:string, id:string) { const res=await fetch(`${supabaseUrl}/rest/v1/${table}?id=eq.${id}`,{method:"DELETE",headers:h(token)}); if(!res.ok) throw new Error(`${table} silinemedi.`); }
