export type Session = { access_token: string; refresh_token?: string; user?: { id: string; email?: string } };
const url = process.env.NEXT_PUBLIC_SUPABASE_URL || "";
const key = process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY || "";
export const ready = Boolean(url && key);
const h = (token?: string, json=true): HeadersInit => ({ apikey: key, Authorization: `Bearer ${token || key}`, ...(json?{"Content-Type":"application/json"}:{}) });
export async function login(email:string,password:string):Promise<Session>{const r=await fetch(`${url}/auth/v1/token?grant_type=password`,{method:"POST",headers:h(undefined),body:JSON.stringify({email,password})});const d=await r.json(); if(!r.ok) throw new Error(d.error_description||d.msg||"Giriş yapılamadı"); return d;}
export async function register(email:string,password:string):Promise<Session>{const r=await fetch(`${url}/auth/v1/signup`,{method:"POST",headers:h(undefined),body:JSON.stringify({email,password})});const d=await r.json(); if(!r.ok) throw new Error(d.error_description||d.msg||"Kayıt oluşturulamadı"); return d;}
export async function select<T>(table:string,token:string,query="select=*&order=created_at.desc"):Promise<T[]>{const r=await fetch(`${url}/rest/v1/${table}?${query}`,{headers:h(token),cache:"no-store"});const d=await r.json(); if(!r.ok) throw new Error(d.message||`${table} okunamadı`); return d;}
export async function insert<T>(table:string,token:string,payload:any):Promise<T>{const r=await fetch(`${url}/rest/v1/${table}`,{method:"POST",headers:{...h(token),Prefer:"return=representation"},body:JSON.stringify(payload)});const d=await r.json(); if(!r.ok) throw new Error(d.message||`${table} kaydedilemedi`); return d[0];}
export async function update<T>(table:string,token:string,id:string,payload:any):Promise<T>{const r=await fetch(`${url}/rest/v1/${table}?id=eq.${id}`,{method:"PATCH",headers:{...h(token),Prefer:"return=representation"},body:JSON.stringify(payload)});const d=await r.json(); if(!r.ok) throw new Error(d.message||`${table} güncellenemedi`); return d[0];}
export async function del(table:string,token:string,id:string){const r=await fetch(`${url}/rest/v1/${table}?id=eq.${id}`,{method:"DELETE",headers:h(token)}); if(!r.ok){let d:any={};try{d=await r.json()}catch{} throw new Error(d.message||`${table} silinemedi`);}}
export async function upload(token:string,path:string,file:File){const r=await fetch(`${url}/storage/v1/object/player-images/${path}`,{method:"POST",headers:{apikey:key,Authorization:`Bearer ${token}`,"x-upsert":"true","Content-Type":file.type||"application/octet-stream"},body:file});const d=await r.json().catch(()=>({})); if(!r.ok) throw new Error(d.message||"Fotoğraf yüklenemedi"); return `${url}/storage/v1/object/public/player-images/${path}`;}
