
const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || "";
const publishableKey = process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY || "";
export const supabaseReady = Boolean(supabaseUrl && publishableKey);
const h=(token?:string,json=true)=>{const x:any={apikey:publishableKey,Authorization:`Bearer ${token||publishableKey}`}; if(json)x["Content-Type"]="application/json"; return x};
export async function authLogin(email:string,password:string){const r=await fetch(`${supabaseUrl}/auth/v1/token?grant_type=password`,{method:'POST',headers:{apikey:publishableKey,'Content-Type':'application/json'},body:JSON.stringify({email,password})});const d=await r.json();if(!r.ok)throw new Error(d.error_description||d.msg||'Giriş yapılamadı');return d}
export async function authRegister(email:string,password:string){const r=await fetch(`${supabaseUrl}/auth/v1/signup`,{method:'POST',headers:{apikey:publishableKey,'Content-Type':'application/json'},body:JSON.stringify({email,password})});const d=await r.json();if(!r.ok)throw new Error(d.error_description||d.msg||'Kayıt oluşturulamadı');return d}
export async function sel(table:string,token:string,query='select=*&order=created_at.desc'){const r=await fetch(`${supabaseUrl}/rest/v1/${table}?${query}`,{headers:h(token),cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.message||`${table} okunamadı`);return d}
export async function ins(table:string,token:string,payload:any){const r=await fetch(`${supabaseUrl}/rest/v1/${table}`,{method:'POST',headers:{...h(token),Prefer:'return=representation'},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw new Error(d.message||`${table} kaydedilemedi`);return d[0]}
export async function upd(table:string,token:string,id:string,payload:any){const r=await fetch(`${supabaseUrl}/rest/v1/${table}?id=eq.${id}`,{method:'PATCH',headers:{...h(token),Prefer:'return=representation'},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw new Error(d.message||`${table} güncellenemedi`);return d[0]}
export async function del(table:string,token:string,id:string){const r=await fetch(`${supabaseUrl}/rest/v1/${table}?id=eq.${id}`,{method:'DELETE',headers:h(token)});if(!r.ok){let d:any={};try{d=await r.json()}catch{};throw new Error(d.message||`${table} silinemedi`)}}
export async function upload(bucket:string,token:string,path:string,file:File){const r=await fetch(`${supabaseUrl}/storage/v1/object/${bucket}/${path}`,{method:'POST',headers:{apikey:publishableKey,Authorization:`Bearer ${token}`,'x-upsert':'true','Content-Type':file.type||'application/octet-stream'},body:file});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||'Dosya yüklenemedi');return `${supabaseUrl}/storage/v1/object/public/${bucket}/${path}`}
