-- ScoutCore V10 Enterprise Ek Kurulum / Migration
-- Supabase > SQL Editor > New Query içine yapıştırıp RUN çalıştırın.
-- Mevcut V9 tablolarını bozmaz; yeni profesyonel modülleri ekler.
create extension if not exists "pgcrypto";
create table if not exists public.player_documents (id uuid primary key default gen_random_uuid(),player_id uuid not null references public.players(id) on delete cascade,file_name text not null,file_type text default '',file_url text not null,note text default '',created_by uuid references auth.users(id),created_at timestamptz default now());
create table if not exists public.player_videos (id uuid primary key default gen_random_uuid(),player_id uuid not null references public.players(id) on delete cascade,title text not null,video_url text not null,video_type text default 'Link',note text default '',created_by uuid references auth.users(id),created_at timestamptz default now());
create table if not exists public.transfer_committee (id uuid primary key default gen_random_uuid(),player_id uuid references public.players(id) on delete cascade,player_name text default '',stage text default 'Komite',priority text default 'Normal',transfer_type text default 'Satın Alma',fee text default '',salary text default '',committee_note text default '',decision_status text default 'Bekliyor',yes_votes int default 0,no_votes int default 0,created_by uuid references auth.users(id),created_at timestamptz default now(),updated_at timestamptz default now());
create table if not exists public.budget_plans (id uuid primary key default gen_random_uuid(),title text not null,transfer_budget numeric default 0,salary_budget numeric default 0,planned_fee numeric default 0,planned_salary numeric default 0,note text default '',created_by uuid references auth.users(id),created_at timestamptz default now());
create table if not exists public.notifications (id uuid primary key default gen_random_uuid(),title text not null,detail text default '',notification_type text default 'Bilgi',is_read boolean default false,created_by uuid references auth.users(id),created_at timestamptz default now());
alter table public.player_documents enable row level security;alter table public.player_videos enable row level security;alter table public.transfer_committee enable row level security;alter table public.budget_plans enable row level security;alter table public.notifications enable row level security;
drop policy if exists "player_documents all access" on public.player_documents;create policy "player_documents all access" on public.player_documents for all to anon, authenticated using (true) with check (true);
drop policy if exists "player_videos all access" on public.player_videos;create policy "player_videos all access" on public.player_videos for all to anon, authenticated using (true) with check (true);
drop policy if exists "transfer_committee all access" on public.transfer_committee;create policy "transfer_committee all access" on public.transfer_committee for all to anon, authenticated using (true) with check (true);
drop policy if exists "budget_plans all access" on public.budget_plans;create policy "budget_plans all access" on public.budget_plans for all to anon, authenticated using (true) with check (true);
drop policy if exists "notifications all access" on public.notifications;create policy "notifications all access" on public.notifications for all to anon, authenticated using (true) with check (true);
insert into storage.buckets (id,name,public) values ('player-documents','player-documents',true) on conflict (id) do update set public=true;
insert into storage.buckets (id,name,public) values ('player-videos','player-videos',true) on conflict (id) do update set public=true;
drop policy if exists "player documents public read" on storage.objects;create policy "player documents public read" on storage.objects for select to public using (bucket_id='player-documents');
drop policy if exists "player documents authenticated upload" on storage.objects;create policy "player documents authenticated upload" on storage.objects for insert to authenticated with check (bucket_id='player-documents');
drop policy if exists "player documents authenticated update" on storage.objects;create policy "player documents authenticated update" on storage.objects for update to authenticated using (bucket_id='player-documents') with check (bucket_id='player-documents');
drop policy if exists "player videos public read" on storage.objects;create policy "player videos public read" on storage.objects for select to public using (bucket_id='player-videos');
drop policy if exists "player videos authenticated upload" on storage.objects;create policy "player videos authenticated upload" on storage.objects for insert to authenticated with check (bucket_id='player-videos');
drop policy if exists "player videos authenticated update" on storage.objects;create policy "player videos authenticated update" on storage.objects for update to authenticated using (bucket_id='player-videos') with check (bucket_id='player-videos');
