'use client';
import Link from "next/link";
import { useMemo, useState } from "react";
import { Badge } from "@/components/Badge";
import { badgeClass, positionTabs, folderTabs, statusLabel, folderLabel } from "@/lib/labels";
type Player = { id:string; name:string; photoUrl?:string; age?:number; position?:string; positionGroup:string; transferFolder:string; club?:string; contractEnd?:string; apps:number; goals:number; assists:number; minutes:number; transferScore:number; status:string; clubInterest?:string; };
const emptyForm = { name:"", photoUrl:"", age:"", position:"", positionGroup:"ORTA_SAHA", transferFolder:"TAKIP_LISTESI", club:"", contractEnd:"", apps:"", goals:"", assists:"", minutes:"", transferScore:"70", status:"WATCHING", clubInterest:"İzleniyor" };
export default function PlayersClient({ initialPlayers }: { initialPlayers: Player[] }) {
 const [players,setPlayers]=useState<Player[]>(initialPlayers); const [activePos,setActivePos]=useState("ALL"); const [activeFolder,setActiveFolder]=useState("ALL"); const [form,setForm]=useState<any>(emptyForm); const [editingId,setEditingId]=useState<string|null>(null);
 const filtered=useMemo(()=>players.filter(p=>(activePos==="ALL"||p.positionGroup===activePos)&&(activeFolder==="ALL"||p.transferFolder===activeFolder)),[players,activePos,activeFolder]);
 function count(pos:string, folder?:string){return players.filter(p=>(pos==="ALL"||p.positionGroup===pos)&&(!folder||folder==="ALL"||p.transferFolder===folder)).length}
 function setField(k:string,v:string){setForm({...form,[k]:v})}
 async function savePlayer(){if(!form.name)return alert("Oyuncu adı zorunlu"); const method=editingId?"PUT":"POST"; const url=editingId?`/api/players/${editingId}`:"/api/players"; const res=await fetch(url,{method,headers:{"Content-Type":"application/json"},body:JSON.stringify(form)}); const saved=await res.json(); if(editingId)setPlayers(players.map(p=>p.id===editingId?saved:p)); else setPlayers([saved,...players]); setForm(emptyForm); setEditingId(null)}
 function editPlayer(p:Player){setEditingId(p.id);setForm({...emptyForm,...p});window.scrollTo({top:0,behavior:"smooth"})}
 async function deletePlayer(id:string){if(!confirm("Oyuncu silinsin mi?"))return;await fetch(`/api/players/${id}`,{method:"DELETE"});setPlayers(players.filter(p=>p.id!==id))}
 return <><div className="panel"><div className="panelHead"><div><h3>{editingId?"Oyuncu Düzenle":"Oyuncu Ekle"}</h3><p className="muted">Oyuncuyu pozisyon klasörü + transfer klasörüne yerleştir.</p></div>{editingId&&<button className="btn secondary" onClick={()=>{setEditingId(null);setForm(emptyForm)}}>İptal</button>}</div><div className="formGrid">
 <input className="input" value={form.name} onChange={e=>setField("name",e.target.value)} placeholder="Oyuncu adı"/><input className="input" value={form.photoUrl||""} onChange={e=>setField("photoUrl",e.target.value)} placeholder="Fotoğraf URL"/><input className="input" value={form.age||""} onChange={e=>setField("age",e.target.value)} placeholder="Yaş"/><input className="input" value={form.position||""} onChange={e=>setField("position",e.target.value)} placeholder="Mevki"/>
 <select className="input" value={form.positionGroup} onChange={e=>setField("positionGroup",e.target.value)}>{positionTabs.filter(t=>t.key!=="ALL").map(t=><option key={t.key} value={t.key}>{t.label}</option>)}</select><select className="input" value={form.transferFolder} onChange={e=>setField("transferFolder",e.target.value)}>{folderTabs.filter(t=>t.key!=="ALL").map(t=><option key={t.key} value={t.key}>{t.label}</option>)}</select>
 <input className="input" value={form.club||""} onChange={e=>setField("club",e.target.value)} placeholder="Kulüp"/><input className="input" value={form.contractEnd||""} onChange={e=>setField("contractEnd",e.target.value)} placeholder="Sözleşme"/><input className="input" value={form.apps||""} onChange={e=>setField("apps",e.target.value)} placeholder="Maç"/><input className="input" value={form.goals||""} onChange={e=>setField("goals",e.target.value)} placeholder="Gol"/><input className="input" value={form.assists||""} onChange={e=>setField("assists",e.target.value)} placeholder="Asist"/><input className="input" value={form.minutes||""} onChange={e=>setField("minutes",e.target.value)} placeholder="Dakika"/><input className="input" value={form.transferScore||""} onChange={e=>setField("transferScore",e.target.value)} placeholder="Skor"/><select className="input" value={form.status} onChange={e=>setField("status",e.target.value)}><option value="A_TARGET">A Hedef</option><option value="B_TARGET">B Hedef</option><option value="C_WATCH">C Takip</option><option value="WATCHING">İzleme</option><option value="REJECTED">Önerilmez</option></select><input className="input" value={form.clubInterest||""} onChange={e=>setField("clubInterest",e.target.value)} placeholder="Kulüp ilgisi"/></div><button className="btn" onClick={savePlayer}>{editingId?"Güncelle":"Oyuncu Ekle"}</button></div>
 <div className="treeBox" style={{marginTop:18}}><div className="folderTree"><h4>Oyuncu Klasör Ağacı</h4>{positionTabs.map(pos=><div key={pos.key} style={{marginBottom:8}}><div className="treeItem" onClick={()=>{setActivePos(pos.key);setActiveFolder("ALL")}}><span>📁 {pos.label}</span><span className="countPill">{count(pos.key)}</span></div>{pos.key!=="ALL"&&folderTabs.filter(f=>f.key!=="ALL").map(f=><div key={f.key} className="treeItem" style={{paddingLeft:26}} onClick={()=>{setActivePos(pos.key);setActiveFolder(f.key)}}><span>└ {f.label}</span><span className="countPill">{count(pos.key,f.key)}</span></div>)}</div>)}</div>
 <div className="panel"><div className="panelHead"><div><h3>Oyuncu Listesi</h3><p className="muted">{filtered.length} oyuncu · İsme tıkla, tam profil ve rapor açılsın.</p></div></div><div className="tabs">{positionTabs.map(t=><button key={t.key} className={`tab ${activePos===t.key?"active":""}`} onClick={()=>setActivePos(t.key)}>{t.label}</button>)}</div><div className="tabs">{folderTabs.map(t=><button key={t.key} className={`tab ${activeFolder===t.key?"active":""}`} onClick={()=>setActiveFolder(t.key)}>{t.label}</button>)}</div><table><thead><tr><th>Oyuncu</th><th>Yaş</th><th>Mevki</th><th>Klasör</th><th>Kulüp</th><th>Maç</th><th>G/A</th><th>Dakika</th><th>Skor</th><th>İlgi</th><th>İşlem</th></tr></thead><tbody>{filtered.map(p=><tr key={p.id}><td><img src={p.photoUrl||"/uploads/player-placeholder-cm.svg"} className="photoMini"/><Link href={`/players/${p.id}`}>{p.name}</Link></td><td>{p.age}</td><td>{p.position}</td><td>{folderLabel(p.transferFolder)}</td><td>{p.club}</td><td>{p.apps}</td><td>{p.goals}/{p.assists}</td><td>{p.minutes}</td><td>{p.transferScore}</td><td>{p.clubInterest}</td><td><div className="actions"><button className="btn secondary" onClick={()=>editPlayer(p)}>Düzenle</button><button className="btn danger" onClick={()=>deletePlayer(p.id)}>Sil</button></div></td></tr>)}</tbody></table></div></div></>;
}
