import { NextRequest,NextResponse } from 'next/server';
import {inflateRawSync} from 'node:zlib';
export const runtime='nodejs';
const decode=(s:string)=>s.replace(/&quot;/g,'"').replace(/&apos;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&amp;/g,'&');
function attrs(s:string){const o:Record<string,string>={};for(const m of s.matchAll(/([\w:.-]+)="([^"]*)"/g))o[m[1]]=decode(m[2]);return o}
function filesOf(buf:Buffer){const files:Record<string,string>={};let e=-1;for(let i=buf.length-22;i>=Math.max(0,buf.length-65557);i--){if(buf.readUInt32LE(i)===0x06054b50){e=i;break}}if(e<0)throw Error('Geçerli XLSX/ZIP dosyası değil.');let off=buf.readUInt32LE(e+16);const n=buf.readUInt16LE(e+10);for(let i=0;i<n;i++){if(buf.readUInt32LE(off)!==0x02014b50)break;const method=buf.readUInt16LE(off+10),size=buf.readUInt32LE(off+20),len=buf.readUInt16LE(off+28),ex=buf.readUInt16LE(off+30),co=buf.readUInt16LE(off+32),loc=buf.readUInt32LE(off+42),name=buf.subarray(off+46,off+46+len).toString();off+=46+len+ex+co;if(!name.endsWith('.xml')&&!name.endsWith('.rels'))continue;if(buf.readUInt32LE(loc)!==0x04034b50)continue;const start=loc+30+buf.readUInt16LE(loc+26)+buf.readUInt16LE(loc+28);const b=buf.subarray(start,start+size);files[name]=(method===8?inflateRawSync(b):b).toString('utf8')}return files}
function txt(v:string){return decode(v.replace(/<[^>]+>/g,''))}
function date(v:string){if(!v)return null;const x=Number(v);if(!Number.isNaN(x)&&x>20000&&x<100000)return new Date(Date.UTC(1899,11,30)+x*86400000).toISOString().slice(0,10);return /^\d{4}-\d{2}-\d{2}$/.test(v)?v:null}
function parse(buf:Buffer){const files=filesOf(buf),wb=files['xl/workbook.xml'];if(!wb)throw Error('Excel çalışma kitabı bulunamadı.');const rels=files['xl/_rels/workbook.xml.rels']||'';const relMap:Record<string,string>={};for(const m of rels.matchAll(/<Relationship\b([^>]*?)\/?\s*>/g)){const a=attrs(m[1]);relMap[a.Id]=a.Target?.replace(/^\//,'')||''}
const ss:string[]=[];for(const m of (files['xl/sharedStrings.xml']||'').matchAll(/<si\b[^>]*>([\s\S]*?)<\/si>/g))ss.push(Array.from(m[1].matchAll(/<t(?:\s[^>]*)?>([\s\S]*?)<\/t>/g)).map(x=>decode(x[1])).join(''));
const out:any[]=[];const seen=new Set<string>();for(const sm of wb.matchAll(/<sheet\b([^>]*?)\/?\s*>/g)){const sh=attrs(sm[1]);let path=relMap[sh['r:id']]||'';if(!path)continue;if(!path.startsWith('xl/'))path='xl/'+path.replace(/^\.\.\//,'');const xml=files[path];if(!xml)continue;const sheet=sh.name||'';if(/dashboard|liste|sözleşme|izlenecek|veri merkezi|kadro|maçlar/i.test(sheet))continue;let headers:Record<string,string>={};for(const rm of xml.matchAll(/<row\b([^>]*?)>([\s\S]*?)<\/row>/g)){const row=Number(attrs(rm[1]).r),cells:Record<string,string>={};for(const cm of rm[2].matchAll(/<c\b([^>]*?)(?:\/>|>([\s\S]*?)<\/c>)/g)){const a=attrs(cm[1]),col=(a.r||'').match(/^[A-Z]+/)?.[0];if(!col)continue;const content=cm[2]||'',v=content.match(/<v>([\s\S]*?)<\/v>/)?.[1]||'', inline=content.match(/<is>([\s\S]*?)<\/is>/)?.[1]||'';let value=a.t==='s'?ss[Number(v)]||'':a.t==='inlineStr'?txt(inline):decode(v);if(value&&value!=='None')cells[col]=value}
if(row===3){headers=cells;continue}if(row<4)continue;const firstCol=headers.B?.toLocaleLowerCase('tr-TR').includes('adı')?'B':'A';const name=(cells[firstCol]||'').trim();if(!name||/^(adı soyadı|sıra no|none)$/i.test(name)||name==='0')continue;const key=name.toLocaleLowerCase('tr-TR')+'|'+(cells.C||'');if(seen.has(key))continue;seen.add(key);
const isB=firstCol==='B';const position=(isB?cells.E:cells.E)||sheet.replace(/ler$|lar$/i,'');const result={name,position,birth_date:date(isB?cells.C:cells.C),nationality:isB?'':cells.B||'',country:isB?(headers.H?.includes('Ülke')?cells.H||'':'Türkiye'):cells.B||'',club:isB?cells.G||'':cells.G||'',contract_end:date(isB?cells.I:cells.H),status:isB?(cells.Q||''):(cells.I||''),foot:isB?cells.F||'':'',league:headers.H?.includes('Lig')?cells.H||'':'',external_link:'',excel_sheet:sheet,excel_row:row,excel_fields:Object.fromEntries(Object.entries(cells).map(([k,v])=>[headers[k]||k,v]))};out.push(result)
}}return out}
export async function POST(req:NextRequest){try{const form=await req.formData();const file=form.get('file');if(!(file instanceof File))return NextResponse.json({error:'Excel dosyası seçilmedi.'},{status:400});if(file.size>12*1024*1024)return NextResponse.json({error:'Dosya 12 MB sınırını aşıyor.'},{status:413});if(!/\.xlsx$/i.test(file.name))return NextResponse.json({error:'Yalnızca .xlsx destekleniyor.'},{status:400});const rows=parse(Buffer.from(await file.arrayBuffer()));return NextResponse.json({rows,count:rows.length})}catch(e:any){return NextResponse.json({error:e.message||'Dosya okunamadı.'},{status:400})}}
