import { prisma } from "@/lib/prisma";
import { Shell } from "@/components/Shell";
import { Badge } from "@/components/Badge";
import { badgeClass, statusLabel, stageLabel, folderLabel } from "@/lib/labels";
import { notFound } from "next/navigation";
import ReportForm from "./report-form";
export default async function PlayerDetail({ params }: { params: { id: string } }) {
 const player = await prisma.player.findUnique({ where: { id: params.id }, include: { reports: { orderBy: { createdAt: "desc" } } } });
 if (!player) return notFound(); const latest = player.reports[0];
 return <Shell active="players" title={player.name} subtitle="Yönetici oyuncu profil ve rapor ekranı"><div className="profileGrid"><div className="panel photoPanel"><img src={player.photoUrl || "/uploads/player-placeholder-cm.svg"} className="playerPhoto"/><h2>{player.name}</h2><Badge type={badgeClass(player.status)}>{statusLabel(player.status)}</Badge><p className="muted">{folderLabel(player.transferFolder)}</p></div><div><div className="cards"><div className="card"><span>Yaş</span><strong>{player.age}</strong><em className="muted">Profil</em></div><div className="card"><span>Mevki</span><strong>{player.position}</strong><em className="muted">{player.club}</em></div><div className="card"><span>Sözleşme</span><strong style={{fontSize:24}}>{player.contractEnd}</strong><em className="muted">Kontrat alarmı</em></div><div className="card"><span>Skor</span><strong>{player.transferScore}</strong><em className="muted">{stageLabel(player.stage)}</em></div></div><div className="panel"><h3>Oyuncu Bilgileri ve İstatistikleri</h3><table><tbody><tr><th>Kulüp</th><td>{player.club}</td><th>Kulüp İlgisi</th><td>{player.clubInterest || "-"}</td></tr><tr><th>Maç</th><td>{player.apps}</td><th>Gol</th><td>{player.goals}</td></tr><tr><th>Asist</th><td>{player.assists}</td><th>Dakika</th><td>{player.minutes}</td></tr><tr><th>Teknik</th><td>{player.technical}</td><th>Taktik</th><td>{player.tactical}</td></tr><tr><th>Fizik</th><td>{player.physical}</td><th>Mental</th><td>{player.mental}</td></tr></tbody></table></div></div></div><div className="grid2"><div className="panel"><h3>Yönetici Özet Raporu</h3><p>{latest?.report || "Rapor yok."}</p><h3>Güçlü Yönler</h3><p>{latest?.strengths || "-"}</p><h3>Gelişim Alanları / Risk</h3><p>{latest?.weaknesses || "-"}</p><h3>Önerilen Aksiyon</h3><p>{latest?.action || "-"}</p></div><div className="panel"><h3>Rapor Geçmişi</h3><table><thead><tr><th>Tarih</th><th>Karar</th><th>Maç</th></tr></thead><tbody>{player.reports.map(r=><tr key={r.id}><td>{new Date(r.createdAt).toLocaleDateString("tr-TR")}</td><td>{r.decision || "-"}</td><td>{r.match || "-"}</td></tr>)}</tbody></table></div></div><div className="panel" style={{marginTop:18}}><h3>Yeni Rapor Yaz</h3><ReportForm playerId={player.id}/></div></Shell>;
}
