"use client";
import {useMemo,useState} from "react";

type Player={id:number;name:string;age:number;position:string;club:string;country:string;foot:string;height:string;contract:string;matches:number;goals:number;assists:number;minutes:number;value:string;salary:string;score:number;potential:number;folder:string;status:string;photo:string;report:string;strengths:string;weaknesses:string;action:string;video:string;externalLink:string};
type Scout={id:number;name:string;region:string;role:string;reports:number};

const positions=["Kaleci","Stoper","Sağ Bek","Sol Bek","Ön Libero","8 Numara","10 Numara","Sağ Kanat","Sol Kanat","Forvet"];
const folders=["Acil Transfer","Bu Sezon","Gelecek Sezon","Gelişim","Kiralık","Serbest","Sözleşmesi Bitecek","Takip"];
const tabs=["Home","Players","Scouting","Reports","Video Center","Transfer Center","Analytics","AI Module","Settings"];
const seed:Player[]=[
{id:1,name:"Marko Petrovic",age:23,position:"Forvet",club:"FK Novi",country:"Sırbistan",foot:"Sağ",height:"1.86",contract:"2027",matches:31,goals:14,assists:5,minutes:2410,value:"650K €",salary:"18K €/ay",score:84,potential:87,folder:"Acil Transfer",status:"A Hedef",photo:"",report:"Ceza sahası koşuları güçlü. İlk temas kalitesi iyi. Transfer komitesi için uygun aday.",strengths:"Bitiricilik, koşu zamanlaması, pres",weaknesses:"Sırtı dönük oyun",action:"Komiteye sun",video:"https://youtube.com",externalLink:""},
{id:2,name:"Ali Can",age:22,position:"Orta Saha",club:"Anadolu FK",country:"Türkiye",foot:"Sağ",height:"1.78",contract:"2026",matches:34,goals:4,assists:9,minutes:2880,value:"400K €",salary:"320K ₺/ay",score:79,potential:84,folder:"Gelecek Sezon",status:"B Hedef",photo:"",report:"Topla çıkış ve bağlantı oyununda değerli. Fiziksel temas seviyesi izlenmeli.",strengths:"Pas açısı, oyun görüşü, duran top",weaknesses:"Savunma geçişi",action:"2 maç daha izle",video:"",externalLink:""},
{id:3,name:"Uğurcan Kaya",age:25,position:"Kaleci",club:"Anadolu FK",country:"Türkiye",foot:"Sağ",height:"1.91",contract:"2028",matches:32,goals:0,assists:0,minutes:2880,value:"550K €",salary:"420K ₺/ay",score:81,potential:83,folder:"Acil Transfer",status:"A Hedef",photo:"",report:"Refleks, yan top ve iletişim seviyesi iyi. Ayakla oyun gelişebilir.",strengths:"Refleks, yan top, iletişim",weaknesses:"Uzun pas isabeti",action:"Canlı izleme planla",video:"",externalLink:""}];
const scoutSeed:Scout[]=[{id:1,name:"Scout A",region:"Balkanlar",role:"Senior Scout",reports:18},{id:2,name:"Scout B",region:"Türkiye",role:"Area Scout",reports:12},{id:3,name:"Scout C",region:"Afrika",role:"Video Scout",reports:9}];
const blank:Player={id:0,name:"",age:23,position:"Stoper",club:"",country:"",foot:"Sağ",height:"1.85",contract:"2027",matches:0,goals:0,assists:0,minutes:0,value:"",salary:"",score:70,potential:75,folder:"Takip",status:"Takip",photo:"",report:"",strengths:"",weaknesses:"",action:"",video:"",externalLink:""};

export default function App(){
 const[logged,setLogged]=useState(false),[active,setActive]=useState("Home");
 const[players,setPlayers]=useState<Player[]>(seed),[selected,setSelected]=useState<Player|null>(seed[0]);
 const[scouts,setScouts]=useState<Scout[]>(scoutSeed),[q,setQ]=useState(""),[filter,setFilter]=useState("Tümü"),[editing,setEditing]=useState<Player|null>(null);
 const[newScout,setNewScout]=useState({name:"",region:"",role:"Scout"});
 const filtered=useMemo(()=>players.filter(p=>{const text=`${p.name} ${p.club} ${p.position} ${p.country}`.toLowerCase();return text.includes(q.toLowerCase())&&(filter==="Tümü"||p.position===filter||p.folder===filter||p.status===filter)}),[players,q,filter]);
 function savePlayer(p:Player){const np={...p,id:p.id||Date.now()};setPlayers(players.some(x=>x.id===np.id)?players.map(x=>x.id===np.id?np:x):[np,...players]);setSelected(np);setEditing(null)}
 function del(id:number){const n=players.filter(p=>p.id!==id);setPlayers(n);if(selected?.id===id)setSelected(n[0]||null)}
 function update(p:Player){setSelected(p);setPlayers(players.map(x=>x.id===p.id?p:x))}
 function addScout(){if(!newScout.name.trim())return;setScouts([{id:Date.now(),name:newScout.name,region:newScout.region||"Belirlenecek",role:newScout.role,reports:0},...scouts]);setNewScout({name:"",region:"",role:"Scout"})}
 function exportCSV(){const h=["name","age","position","club","country","matches","goals","assists","minutes","score","potential","status","folder"];const csv=[h.join(","),...players.map(p=>h.map(k=>String((p as any)[k]).replaceAll(","," ")).join(","))].join("\n");const b=new Blob([csv],{type:"text/csv"});const a=document.createElement("a");a.href=URL.createObjectURL(b);a.download="scoutcore_players.csv";a.click()}
 if(!logged)return <Login onLogin={()=>setLogged(true)}/>;
 return <div className="app"><header className="topbar"><button className="brand" onClick={()=>setActive("Home")}><img src="/scoutcore-logo.jpeg" alt="ScoutCore"/></button><nav className="tabs">{tabs.map(t=><button key={t} onClick={()=>setActive(t)} className={active===t?"tab active":"tab"}>{t}</button>)}</nav><div className="profile">Onur Baş</div></header><main className="workspace">
  {active==="Home"&&<Home setActive={setActive} players={players} scouts={scouts}/>}
  {active==="Players"&&<Players players={filtered} selected={selected} q={q} setQ={setQ} filter={filter} setFilter={setFilter} setSelected={setSelected} setActive={setActive} setEditing={setEditing} del={del} exportCSV={exportCSV}/>}
  {active==="Scouting"&&<Scouting players={players} scouts={scouts}/>}
  {active==="Reports"&&<Reports selected={selected} update={update}/>}
  {active==="Video Center"&&<VideoCenter selected={selected} update={update}/>}
  {active==="Transfer Center"&&<Transfer players={players} scouts={scouts} setSelected={setSelected} setActive={setActive} newScout={newScout} setNewScout={setNewScout} addScout={addScout} removeScout={(id:number)=>setScouts(scouts.filter(s=>s.id!==id))}/>}
  {active==="Analytics"&&<Analytics players={players} scouts={scouts}/>}
  {active==="AI Module"&&<AI players={players}/>}
  {active==="Settings"&&<Settings exportCSV={exportCSV}/>}
 </main>{editing&&<Editor player={editing} onSave={savePlayer} onCancel={()=>setEditing(null)}/>}</div>
}
function Login({onLogin}:{onLogin:()=>void}){return <div className="login"><div className="ambient one"/><div className="ambient two"/><section className="loginPanel"><img src="/scoutcore-logo.jpeg" className="loginLogo" alt="ScoutCore"/><div className="loginCard"><h1>Secure Access</h1><p>Football Intelligence Platform</p><label>Username</label><input defaultValue="onur.bas"/><label>Password</label><input defaultValue="ScoutCore2026!" type="password"/><div className="loginOptions"><span>Remember me</span><span>Forgot password?</span></div><button onClick={onLogin}>Login</button></div></section></div>}
function Home({setActive,players,scouts}:{setActive:(x:string)=>void;players:Player[];scouts:Scout[]}){return <section><div className="homeHero"><div><span>SCOUTCORE COMMAND CENTER</span><h1>Football Intelligence Platform</h1><p>Oyuncu takibi, scout raporları, transfer kararları ve performans analizlerini tek merkezde yöneten profesyonel platform.</p></div><div className="homeSignal"><b>{players.length}</b><small>Active Players</small></div></div><div className="quickGrid"><button onClick={()=>setActive("Players")}><b>Players</b><span>Oyuncu veritabanı, PDF, CSV ve profil ekranları</span></button><button onClick={()=>setActive("Transfer Center")}><b>Transfer Center</b><span>Transfer pipeline ve scout ekibi yönetimi</span></button><button onClick={()=>setActive("Reports")}><b>Reports</b><span>Scout raporları, karar notları ve aksiyon planı</span></button><button onClick={()=>setActive("Video Center")}><b>Video Center</b><span>Oyuncu video linkleri ve analiz notları</span></button></div><div className="homeRows"><div className="panel"><h3>Today</h3><Task t="3 oyuncu için son izleme notu bekleniyor"/><Task t="2 A hedef transfer komitesine hazır"/><Task t="Video Center içinde 4 yeni link kontrol edilecek"/></div><div className="panel"><h3>System Snapshot</h3><Metric l="Reports" v="42"/><Metric l="Scouts" v={String(scouts.length)}/><Metric l="Pipeline" v="18"/></div></div><div className="panel positionPanel"><h3>Pozisyon Klasörleri</h3><p className="positionTitle">Dikey klasör yapısı</p><div className="folderList">{positions.map(p=><button key={p} onClick={()=>setActive("Players")}><b>{p}</b><span>Open</span></button>)}</div></div></section>}
function Task({t}:{t:string}){return <div className="task"><span/>{t}</div>}
function Metric({l,v}:{l:string;v:string}){return <div className="miniMetric"><span>{l}</span><b>{v}</b></div>}
function Players(props:any){return <section className="playersLayout"><div className="panel"><div className="sectionHead"><div><h2>Players</h2><p>Oyuncu ekleme, düzenleme, silme, rapor ve PDF çıktısı.</p></div><div className="actions"><button onClick={()=>props.setEditing(blank)}>+ Add Player</button><button onClick={props.exportCSV}>CSV</button><button onClick={()=>window.print()}>PDF</button></div></div><div className="toolbar"><input value={props.q} onChange={(e:any)=>props.setQ(e.target.value)} placeholder="Search player, club, country..."/><select value={props.filter} onChange={(e:any)=>props.setFilter(e.target.value)}><option>Tümü</option>{positions.map(p=><option key={p}>{p}</option>)}{folders.map(f=><option key={f}>{f}</option>)}</select></div><div className="playerRows">{props.players.map((p:Player)=><div className={props.selected?.id===p.id?"playerRow selected":"playerRow"} key={p.id}><button onClick={()=>props.setSelected(p)}><Avatar p={p}/><div><b>{p.name}</b><span>{p.position} · {p.club} · {p.country}</span></div></button><strong>{p.score}</strong><em>{p.status}</em><button onClick={()=>props.setEditing(p)}>Edit</button><button className="danger" onClick={()=>props.del(p.id)}>Delete</button></div>)}</div></div><Profile player={props.selected} onEdit={props.setEditing} onReports={()=>props.setActive("Reports")}/></section>}
function Avatar({p}:{p:Player}){return <div className="avatar">{p.photo?<img src={p.photo} alt={p.name}/>:p.name.split(" ").map(x=>x[0]).slice(0,2).join("")}</div>}
function Profile({player,onEdit,onReports}:{player:Player|null;onEdit:(p:Player)=>void;onReports:()=>void}){if(!player)return <div className="panel">Oyuncu seçilmedi.</div>;return <aside className="panel profilePanel"><div className="profileTop"><div className="bigAvatar">{player.photo?<img src={player.photo} alt={player.name}/>:player.name.split(" ").map(x=>x[0]).slice(0,2).join("")}</div><div><h3>{player.name}</h3><p>{player.position} · {player.club}</p><i>{player.status}</i></div></div><div className="profileScore"><b>{player.score}</b><span>ScoutCore Score</span></div><div className="infoGrid">{[["Age",player.age],["Foot",player.foot],["Height",player.height],["Contract",player.contract],["Matches",player.matches],["Minutes",player.minutes],["Goals",player.goals],["Assists",player.assists],["Value",player.value],["Salary",player.salary]].map(([l,v])=><div className="info" key={String(l)}><span>{String(l)}</span><b>{String(v||"-")}</b></div>)}</div><div className="profileActions"><button onClick={()=>onEdit(player)}>Edit Profile</button><button onClick={onReports}>Report</button><button onClick={()=>window.print()}>PDF</button></div></aside>}
function Editor({player,onSave,onCancel}:{player:Player;onSave:(p:Player)=>void;onCancel:()=>void}){const[p,setP]=useState(player);function u(k:keyof Player,v:any){setP({...p,[k]:v})}return <div className="modal"><div className="editor"><h2>{p.id?"Edit Player":"Add Player"}</h2><div className="editorGrid"><input placeholder="Name" value={p.name} onChange={e=>u("name",e.target.value)}/><select value={p.position} onChange={e=>u("position",e.target.value)}>{positions.map(x=><option key={x}>{x}</option>)}</select><input placeholder="Club" value={p.club} onChange={e=>u("club",e.target.value)}/><input placeholder="Country" value={p.country} onChange={e=>u("country",e.target.value)}/><input placeholder="Photo URL" value={p.photo} onChange={e=>u("photo",e.target.value)}/><input placeholder="Age" value={p.age} onChange={e=>u("age",Number(e.target.value)||0)}/><input placeholder="Height" value={p.height} onChange={e=>u("height",e.target.value)}/><input placeholder="Foot" value={p.foot} onChange={e=>u("foot",e.target.value)}/><input placeholder="Contract" value={p.contract} onChange={e=>u("contract",e.target.value)}/><input placeholder="Value" value={p.value} onChange={e=>u("value",e.target.value)}/><input placeholder="Score" value={p.score} onChange={e=>u("score",Number(e.target.value)||0)}/><select value={p.folder} onChange={e=>u("folder",e.target.value)}>{folders.map(x=><option key={x}>{x}</option>)}</select></div><div className="modalActions"><button onClick={()=>onSave(p)}>Save</button><button onClick={onCancel}>Cancel</button></div></div></div>}
function Scouting({players,scouts}:{players:Player[];scouts:Scout[]}){return <section className="twoCol"><div className="panel"><h2>Scouting</h2><p>Aktif scout görevleri ve oyuncu izleme akışı.</p>{players.map(p=><Task key={p.id} t={`${p.name} için ${p.action}`}/>)}</div><div className="panel"><h3>Scout Team</h3>{scouts.map(s=><div className="scoutCard" key={s.id}><b>{s.name}</b><span>{s.region} · {s.reports} rapor</span></div>)}</div></section>}
function Reports({selected,update}:{selected:Player|null;update:(p:Player)=>void}){if(!selected)return <div className="panel">Oyuncu seçilmedi.</div>;function u(k:keyof Player,v:any){update({...(selected as Player),[k]:v} as Player)}return <section className="panel reportPage"><div className="sectionHead"><div><h2>Reports</h2><p>{selected.name} scout raporu</p></div><button onClick={()=>window.print()}>PDF</button></div><label>Scout Report</label><textarea value={selected.report} onChange={e=>u("report",e.target.value)}/><div className="reportGrid"><div><label>Strengths</label><textarea value={selected.strengths} onChange={e=>u("strengths",e.target.value)}/></div><div><label>Weaknesses</label><textarea value={selected.weaknesses} onChange={e=>u("weaknesses",e.target.value)}/></div></div><label>Action</label><input value={selected.action} onChange={e=>u("action",e.target.value)}/></section>}
function VideoCenter({selected,update}:{selected:Player|null;update:(p:Player)=>void}){if(!selected)return <div className="panel">Oyuncu seçilmedi.</div>;function u(k:keyof Player,v:any){update({...(selected as Player),[k]:v} as Player)}return <section className="videoLayout"><div className="panel"><h2>Video Center</h2><p>Video linkleri ve analiz notları bu alanda yönetilir.</p><label>Video URL</label><input value={selected.video} onChange={e=>u("video",e.target.value)}/><label>External Analysis Link</label><input value={selected.externalLink} onChange={e=>u("externalLink",e.target.value)}/></div><div className="panel videoBox"><div className="play">▶</div><b>{selected.name}</b><span>Video preview area</span></div></section>}
function Transfer({players,scouts,setSelected,setActive,newScout,setNewScout,addScout,removeScout}:any){const stages=["Takip","İzleniyor","Aday","Komite","Onay","Transfer"];return <section className="transferLayout"><div className="pipeline panel"><h2>Transfer Center</h2><div className="pipeGrid">{stages.map(stage=><div className="pipeCol" key={stage}><h3>{stage}</h3>{players.slice(0,3).map((p:Player)=><button key={stage+p.id} onClick={()=>{setSelected(p);setActive("Players")}}><b>{p.name}</b><span>{p.position} · {p.score}</span></button>)}</div>)}</div></div><div className="panel"><h2>Scout Management</h2><div className="scoutForm"><input placeholder="Scout name" value={newScout.name} onChange={(e:any)=>setNewScout({...newScout,name:e.target.value})}/><input placeholder="Region" value={newScout.region} onChange={(e:any)=>setNewScout({...newScout,region:e.target.value})}/><input placeholder="Role" value={newScout.role} onChange={(e:any)=>setNewScout({...newScout,role:e.target.value})}/><button onClick={addScout}>Add Scout</button></div>{scouts.map((s:Scout)=><div className="scoutCard manage" key={s.id}><div><b>{s.name}</b><span>{s.region} · {s.role}</span></div><button onClick={()=>removeScout(s.id)}>Remove</button></div>)}</div></section>}
function Analytics({players,scouts}:{players:Player[];scouts:Scout[]}){return <section className="twoCol"><div className="panel"><h2>Analytics</h2><Bar label="Report Completion" value={82}/><Bar label="A Target Conversion" value={44}/><Bar label="Potential Index" value={71}/><Bar label="Scout Activity" value={76}/></div><div className="panel"><h2>Team Activity</h2>{scouts.map(s=><div className="rank" key={s.id}><b>{s.name}</b><span>{s.reports} reports</span></div>)}</div></section>}
function Bar({label,value}:{label:string;value:number}){return <div className="bar"><div><span>{label}</span><b>{value}%</b></div><i><em style={{width:`${value}%`}}/></i></div>}
function AI({players}:{players:Player[]}){const[prompt,setPrompt]=useState("24 yaş altı, yüksek potansiyelli, maliyeti düşük oyuncuları listele.");const results=players.filter(p=>p.age<=25&&p.potential>=80);return <section className="panel aiPanel"><h2>AI Module</h2><textarea value={prompt} onChange={e=>setPrompt(e.target.value)}/>{results.map(p=><div className="rank" key={p.id}><b>{p.name}</b><span>{p.position} · Potential {p.potential}</span></div>)}</section>}
function Settings({exportCSV}:{exportCSV:()=>void}){return <section className="panel"><h2>Settings</h2><p>ScoutCore arayüz ayarları, dışa aktarım ve sistem yönetimi.</p><div className="actions"><button onClick={exportCSV}>CSV Export</button><button onClick={()=>window.print()}>PDF Print</button></div></section>}
